### ISSUE TITLE
exposed beyond app through Intent.getData()

### ISSUE THREAD

**Issue by san0suke** [Smile-SA/cordova-plugin-fileopener#15]
window.cordova.plugins.FileOpener.openFile("file:///storage/emulated/0/Download/nf.pdf", function(r) {
        console.log("sucesso:", r);
    }, function (r) {
        console.log("erro:", r);
    });
erro:
file:///storage/emulated/0/Download/nf.pdf exposed beyond app through Intent.getData()

**Comment by marob** [comment]
Hi,

it seems to be an Android N-related issue as explained [here](https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed) and [here](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en).

Two solutions:
- change your targetSdkVersion to 23 or lower. It is the easiest solution, but it's only a workaround for now
- follow the recommendations in [the blog post](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en), but it requires modifications in the cordova-plugin-fileopener (you're welcome to submit a pull request) and some configurations in your app (AndroidManifest.xml and res/xml/provider_paths.xml)

Regards

**Comment by jodacame** [comment]
@marob solution #1 worked, thanks

**Comment by frankvlocity** [comment]
> Hi,
> 
> it seems to be an Android N-related issue as explained [here](https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed) and [here](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en).
> 
> Two solutions:
> 
> * change your targetSdkVersion to 23 or lower. It is the easiest solution, but it's only a workaround for now
> * follow the recommendations in [the blog post](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en), but it requires modifications in the cordova-plugin-fileopener (you're welcome to submit a pull request) and some configurations in your app (AndroidManifest.xml and res/xml/provider_paths.xml)
> 
> Regards

Thank you so much for the suggestions!  Both solutions worked! 

- Solution 1: change AndroidManifest.xml file android:targetSdkVersion="23" and clean & rebuild.
- Solution 2: Found a PR does exactly what the blog post described. https://github.com/chingfeng/cordova-plugin-fileopener/commit/474a4cb11941ac17782e099a023c7d57cc110f50

**Comment by marob** [comment]
Indeed the https://github.com/Smile-SA/cordova-plugin-fileopener/pull/18 PR is pending as I have no time nor any project to test it against.
I could merge it but it seems risky without further testing.

**Comment by parshwa1596** [comment]
if targetsdk version is 29 what can i do?

**Comment by marob** [comment]
> if targetsdk version is 29 what can i do?

You can try to use https://github.com/chingfeng/cordova-plugin-fileopener/commit/474a4cb11941ac17782e099a023c7d57cc110f50

**Comment by parshwa1596** [comment]
which file i changed?

**Comment by parshwa1596** [comment]
android.os.FileUriExposedException: file:///storage/emulated/0/Documents/Patidar.pdf exposed beyond app through Intent.getData()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
        at android.net.Uri.checkFileUriExposed(Uri.java:2362)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9901)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9853)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1612)
        at android.app.Activity.startActivityForResult(Activity.java:4555)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4513)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at android.app.Activity.startActivity(Activity.java:4874)
        at android.app.Activity.startActivity(Activity.java:4842)
        at com.patidar.marriagebureau.Activities.Printprofile.previewPdf(Printprofile.java:499)
        at com.patidar.marriagebureau.Activities.Printprofile.createPdf(Printprofile.java:485)
        at com.patidar.marriagebureau.Activities.Printprofile.createPdfWrapper(Printprofile.java:416)
        at com.patidar.marriagebureau.Activities.Printprofile.access$000(Printprofile.java:65)
        at com.patidar.marriagebureau.Activities.Printprofile$1.onClick(Printprofile.java:171)
        at android.view.View.performClick(View.java:6312)
        at android.view.View$PerformClick.run(View.java:24811)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)

I got these error.

**Comment by marob** [comment]
Either the https://github.com/chingfeng/cordova-plugin-fileopener/commit/474a4cb11941ac17782e099a023c7d57cc110f50 version is not working, or you're not really using this version (make sure you clean and rebuild).

**Comment by parshwa1596** [comment]
> android.os.FileUriExposedException: file:///storage/emulated/0/Documents/Patidar.pdf exposed beyond app through Intent.getData()
> at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
> at android.net.Uri.checkFileUriExposed(Uri.java:2362)
> at android.content.Intent.prepareToLeaveProcess(Intent.java:9901)
> at android.content.Intent.prepareToLeaveProcess(Intent.java:9853)
> at android.app.Instrumentation.execStartActivity(Instrumentation.java:1612)
> at android.app.Activity.startActivityForResult(Activity.java:4555)
> at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
> at android.app.Activity.startActivityForResult(Activity.java:4513)
> at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
> at android.app.Activity.startActivity(Activity.java:4874)
> at android.app.Activity.startActivity(Activity.java:4842)
> at com.patidar.marriagebureau.Activities.Printprofile.previewPdf(Printprofile.java:499)
> at com.patidar.marriagebureau.Activities.Printprofile.createPdf(Printprofile.java:485)
> at com.patidar.marriagebureau.Activities.Printprofile.createPdfWrapper(Printprofile.java:416)
> at com.patidar.marriagebureau.Activities.Printprofile.access$000(Printprofile.java:65)
> at com.patidar.marriagebureau.Activities.Printprofile$1.onClick(Printprofile.java:171)
> at android.view.View.performClick(View.java:6312)
> at android.view.View$PerformClick.run(View.java:24811)
> at android.os.Handler.handleCallback(Handler.java:794)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> 
> I got these error.

i got these error in version 29

**Comment by parshwa1596** [comment]
> > if targetsdk version is 29 what can i do?
> 
> You can try to use [chingfeng@474a4cb](https://github.com/chingfeng/cordova-plugin-fileopener/commit/474a4cb11941ac17782e099a023c7d57cc110f50)

i used these?for that error

**Comment by parshwa1596** [comment]
> > if targetsdk version is 29 what can i do?
> 
> You can try to use [chingfeng@474a4cb](https://github.com/chingfeng/cordova-plugin-fileopener/commit/474a4cb11941ac17782e099a023c7d57cc110f50)

not solve using these solution.

**Comment by parshwa1596** [comment]
hi i got profile pic in pdf what can i do?
